// Generated by CoffeeScript 1.10.0
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  window.GameView = (function(superClass) {
    extend(GameView, superClass);

    function GameView() {
      return GameView.__super__.constructor.apply(this, arguments);
    }

    GameView.prototype.className = 'game';

    GameView.prototype.template = _.template('<h2>Winner is: <%= winner %></h2> <div class="player-hand-container"></div> <div class="dealer-hand-container"> <div class="game-view-container"></div>');

    GameView.prototype.initialize = function() {
      this.model.on('change', (function(_this) {
        return function() {
          return _this.render();
        };
      })(this));
      return this.render();
    };

    GameView.prototype.render = function() {
      var winner;
      winner = this.model.get('winner');
      this.$el.html(this.template({
        winner: winner
      }));
      this.$('.dealer-hand-container').html(new HandView({
        collection: this.model.get('dealerHand')
      }).el);
      return this.$('.player-hand-container').html(new HandView({
        collection: this.model.get('playerHand')
      }).el);
    };

    return GameView;

  })(Backbone.View);

}).call(this);

//# sourceMappingURL=GameView.js.map
